global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Blazr.Core;
global using Microsoft.AspNetCore.Mvc;
global using Blazr.App.Core;
global using Microsoft.AspNetCore.Authorization;
